### ISSUE TITLE
About background color of the website

### ISSUE THREAD

**Issue by Hello-Maricel** [SwiftBeta/aprende-swift-feedback#1]
Hola,

¿Sería posible oscurecer un poco el background color del sitio? El color del texto es muy claro y dificulta la lectura.

Muchas gracias.

**Comment by SwiftBeta** [comment]
Hola! lo acabo de arreglar, ahora debería verse bien en light y dark mode. Muchas gracias por abrir la issue 👍

**Comment by Hello-Maricel** [comment]
Quedó perfecta! Muchas gracias 👌
